version: "3"

networks:
  steptodance_default:
    external: true

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: react
    container_name: react
    ports:
      - "5173:80"
    restart: always
    networks:
      - steptodance_default
    environment:
      TZ: Asia/Seoul
